name: notes_final_version
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  google_fonts: 6.1.0
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0
  custom_timer: ^0.1.2
  jiffy: ^5.0.1
  focused_menu: ^1.0.5
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  get: 4.6.6
  pdf: 3.10.7
  get_storage: 2.1.1
  image_cropper: ^5.0.1
  printing: ^5.11.1
  share_plus: ^7.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0


  flutter:
    sdk: flutter
  quill_pdf_converter: ^9.3.1
  flutter_quill: ^9.2.10
  quill_html_converter: ^9.3.1
  flutter_quill_extensions: ^9.3.0
  flutter_svg: ^2.0.10+1
  flutter_zoom_drawer: ^3.2.0
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^5.0.1
  flex_color_picker: ^3.3.1
  flutter_bloc: ^8.1.3
  #  desktop_drop: ^0.4.4
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.3
  flutter_slidable: ^3.0.1
  flutter_native_timezone_updated_gradle: ^2.0.3
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.3
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.18.1
  archive: ^3.4.10
  encrypt: ^5.0.3
  path: ^1.8.3
  permission_handler: ^11.3.1
  local_auth: ^2.1.8
  dio: ^5.4.3+1

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
